config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/projects'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def projects
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortafolioRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--CORE BOOTSTRAP==================================================================================================-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
  <!--===================================================================================================================-->
   <!--SWEETALERT2==================================================================================================-->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <!--===================================================================================================================-->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navbars/navbar_principal" %>
  <%= render "layouts/footer/footer_principal", class:"fixed-bottom" %>



<div class="container"><%= yield %></div>

 <script>
    //==============ANIMAR ICONOS REDES SOCIALES HOVER===========================//
      $('.fa-up').hover(function () {
        $(this).addClass('fa-bounce');
      }, function () {
        $(this).removeClass('fa-bounce');
      });
      //==========================================================================//
      //=============FUNCION  FORMULARIO HABILITAR BOTTON Y ALERTA MENSAJE=============================//
function habilitar(){
    validation1 = document.getElementById("validation01") .value;
    validation2 = document.getElementById("validation02") .value;
    validation3 = document.getElementById("validation03") .value;
    val = 0;

    if(validation1 == ""){
        val++;
    }
    if(validation2 == ""){
        val++;
    }
    if(validation3 == ""){
        val++;
    }
    if(val == 0){
        document.getElementById("btn").disabled = false;
    } else {
        document.getElementById("btn").disabled = true;
    }

}
document.getElementById("validation01").addEventListener("keyup", habilitar);
document.getElementById("validation02").addEventListener("keyup", habilitar);
document.getElementById("validation03").addEventListener("keyup", habilitar);
document.getElementById("btn").addEventListener("click", ()=>{
    Swal.fire({

        position: 'center',
        icon: 'success',
        title: 'Mensaje Enviado Correctamente',
        background: '#fff',
        timerProgressBar: true,
        showConfirmButton: true,
        color: '#d51869',
        timer: 2000
      })

})
//============================================================================//
  </script>



    <!--SCRIPTS JQUERY==========================================================================================-->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <!--========================================================================================================-->

    <!--SCRIPTS FONTAWESOME====================================================================================-->
    <script src="https://kit.fontawesome.com/19e2a818fa.js" crossorigin="anonymous"></script>
    <!--=======================================================================================================-->

  </body>
</html>

app/views/layouts/footer/_footer_principal.html.erb
 <!--FOOTER SECTION ICONOS ANIMADOS=======================================================================-->
    <footer id="footer" class="container-fluid justify-content-center text-center bg-info">
      <div class="row">
        <div class="col col-lg-6">
          <a href="#inicio">
            <i class="text-center col-12 d-lg-none d-block fa-brands fa-space-awesome fa-up  m-3 fa-2x" style="color: #ffffff;"></i></a>
            <h2 class="d-none d-lg-block">MIS REDES</h2>
        </div>
        <div class="col-12 col-lg-6">
          <a href="https://github.com/DiegoSilvaR" target="_blank"><i
              class=" fa-brands fa-square-github fa-up  m-2 fa-3x " style="color: #ffffff;"></i></a>
          <a href="https://www.linkedin.com/in/diego-s-37911841/" target="_blank"><i
              class="fa-brands fa-linkedin  fa-up m-2 fa-3x" style="color: #ffffff;"></i></a>
          <a href="https://twitter.com/Woruskas" target="_blank"><i class="fa-brands fa-square-twitter fa-up m-2 fa-3x"
              style="color: #ffffff;"></i></a>
          <a href="https://www.facebook.com/Worusk" target="_blank"><i
              class="fa-brands fa-square-facebook fa-up m-2 fa-3x" style="color: #ffffff;"></i></a>
        </div>
      </div>
    </footer>
    <!--========================================================================================================-->

app/views/layouts/navbars/_navbar_principal.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container-fluid">
     <%= image_tag 'logo.png', class:"logo-img" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", pages_home_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">

          <%= link_to "Projects", pages_projects_path, class:"nav-link" %>
        </li>
        <li class="nav-item">

          <%= link_to "Contact", pages_contact_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/pages/contact.html.erb
<!--CONTACTO SECTION BOTON ENVIAR EFECTO GLOW CSS CON ALERTA DE ENVIO================================================-->
    <section id="contactos" class="col-lg-11 container-fluid justify-content-center text-start">
      <form class="was-validated">
      <div class="mb-3 mx-3 text-start">
        <label for="validation01" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="validation01" placeholder="Requiere Nombre" required>
         <div class="invalid-feedback">
          Porfavor Ingresa Nombre.
        </div>
      </div>
      <div class="mb-3 mx-3 text-start">
        <label for="validation02" class="form-label">Asunto</label>
        <input type="text" class="form-control" id="validation02" placeholder="Requiere Asunto" required>
        <div class="invalid-feedback">
          Porfavor Ingresa Asunto.
        </div>
      </div>
      <div class="mb-3 mx-3 text-start">
        <label for="validation03" class="form-label">Mensaje</label>
        <textarea class="form-control"  id="validation03" placeholder="Requiere un Mensaje" required
          rows="5"></textarea>
          <div class="invalid-feedback">
            Porfavor Ingresa un mensaje.
          </div>
      </div>
      <div class="col col-md-4 col-lg-3 col-xl-2 mx-3">
        <button type="submit" id="btn" class=" btn btn-info btn-lg text-light form-control glow-on-hover pulse"
          data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="custom-tooltip"
          data-bs-title="Presiona para enviar tu Mensaje." disabled>Enviar</button>
      </div>
    </form>
    </section>
    <!--=====================================================================================================-->

app/views/pages/home.html.erb
 <!--CARRUSEL RESPONSIVO SLIDE AUTOMATICO=======================================================================-->
<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'carrusel1', class:"d-block w-100" %>
    </div>
    <div class="carousel-item ">
        <%= image_tag 'carrusel2', class:"d-block w-100" %>
    </div>
    <div class="carousel-item ">
        <%= image_tag 'carrusel3', class:"d-block w-100" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
    <!--==============================================================================================================-->

app/views/pages/projects.html.erb
 <div class="row">
        <h1 id="quienes" class=" pt-5 pb-3 ">PROYECTOS</h1>
        <hr>
        <div class="col-12 col-md-12 col-lg-12 col-xl-4 px-4" data-bs-toggle="tooltip" data-bs-placement="top"
          data-bs-custom-class="custom-tooltip" data-bs-title="Viaja con Nosotros">
          <button id="viajes" type="button" class="btn btn-info form-control my-3 pulse glow-on-hover">
           <a href="https://diegosilvar.github.io/Ricomida.github.io/" target="_blank">
           <i class="fa-sharp fa-solid fa-plane fa-3x " style="color: #ffffff;"></i></a>
            </button>
          <h1>RICOMIDA</h1>
        </div>
        <div class="col-12 col-md-12 col-lg-12 col-xl-4 px-4">
         <h1>VIAJES CHILE</h1>
          <button id="lugar" type="button" class="btn btn-info form-control my-3 pulse glow-on-hover"
            data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-custom-class="custom-tooltip"
            data-bs-title="Conoce los mejores lugares!">
            <a href="https://diegosilvar.github.io/Viajes_Chile.github.io/" target="_blank">
            <i class="fa-solid fa-mountain fa-3x " style="color: #ffffff;"></i></a></button>
        </div>
        <div class="col-12 col-md-12 col-lg-12 col-xl-4 px-4">
          <button id="mapas" type="button" class="btn btn-info form-control my-3 pulse glow-on-hover"
            data-bs-toggle="tooltip" data-bs-placement="top" data-bs-custom-class="custom-tooltip"
            data-bs-title="Nuestras Rutas y guias Turisticas">
            <i class="fa-solid fa-route fa-3x " style="color: #ffffff;"></i>
          </button>
         <h1>OTROS</h1>
        </div>
      </div>